services:

  backend:
    build:
      context: ./backend
    container_name: task_backend
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: task_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  db:
    image: postgres:15
    container_name: task_db
    restart: always
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpassword
    ports:
      - "5432:5432"